### ISSUE TITLE
[FEATURE]  Allow filtering by Tag.

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#47] opened 2023-01-24 01:12 UTC
I would like to be able to filter "Broken" or "Folder" or by any tag and only show those mods that fit the criteria.

**Comment by jtsage** [comment] 2023-01-24 01:18
I've been thinking on this several times.  the problem is, if I do a dedicated UI for it, it takes up a bunch of space.  As of now, those tags *are* included in the full text search though - e.g. something like this:

![2023-01-23 20_17_52-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/214193310-93d1f8c4-25dd-45d0-8e71-0b484c011abe.png)

I am open to other UI design on this though if you have a good idea.

**Comment by jtsage** [comment] 2023-01-24 02:30
Hmm.  I'm wondering if having it fixed on the top might not be better.  I would then have room for something like a drop-down multi select for tags.  

The rationale behind resetting the filters on collection change was that it hides, and having a filter active that you can't see is no good at all - but you are right in that it sort of happens now with long lists.  Let me play with this a bit in a development branch and see what I can come up with.

As regards to you using it to test in progress mods - yes, us too.  We actually have a back burner project going that will only load a *single* mod, but give you a *ton* more info on it.  It's kinda stuck in "not enough hours in the day" land at the moment, but I suspect I'll be back to it soon.  My goal is to have it include the vast majority of the stuff that testrunner looks for, along with a whole bunch of stuff that testrunner does not look at.

**Comment by ScootersWorkbench** [comment] 2023-01-24 03:38
The developer version sounds great.   I am available for testing if you would like. :)   Currently I am an IT Enterprise Architect and I haven't written any code for about 15 yrs,  but I started out as a developer so I can at least read it.  LOL.   Overall what you have is awesome.   I love being able to see the picture because the name & filename are not always represented properly.   Keep up the great work.   Let me know if you need a pain in the butt to look at anything.  :)

**Comment by jtsage** [comment] 2023-01-24 04:01
Haha.  cool.  I think we actually hang out in similar places on discord as it happens (authentic, official, vertex, north sim, couple others) - I'm the very inventive `JTSage` or `FSG | JTSage` depending on the place.

I will shoot you a test version if you like when I get that far, in the meantime, how bout something along these lines:

![2023-01-23 23_00_45-#🔔-github-commits _ FSG Modding Private - Discord](https://user-images.githubusercontent.com/605986/214209734-d34dfe18-4364-4f6f-a247-330d6479201e.png)

Of course, I just broke all of the filter features, but I think I like the fixed top UI better - makes more sense in my mind anyway

**Comment by ScootersWorkbench** [comment] 2023-01-24 04:05
I think that UI is really good.   But of course there is a balance to what you broke. :)    But having that static at the top will be better for the user.   It really takes out the scrolling,  especially when you select a mod you didn't realize at the top and you are pages deep in the scroll.

**Comment by jtsage** [comment] 2023-01-24 04:14
I agree.  Just messing with the visuals a bit more, and I'll get to re-writing the filter code sometime tomorrow probably.  Thanks for the feedback

![2023-01-23 23_14_00-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/214210981-6bf819f5-ee50-419b-b59e-d21a43d59e44.png)

**Comment by jtsage** [comment] 2023-01-25 02:07
So, I got as far as a pre-release.  Should be stable, I'm gonna mess with a few days to make sure.  

It's available here: https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v1.9.9

I'm not 100% certain, but using a pre-release might make it that it won't auto-update to 2.0.0 when it comes out - but I'm not sure on that.

**Comment by ScootersWorkbench** [comment] 2023-01-26 04:52
The new UI is great!   Also I love that mod count is on the folder.   Great Addition.   Thanks for taking the feedback.

**Comment by jtsage** [comment] 2023-01-26 05:12
you bet!  I like it a whole lot better too!

**Closed by jtsage** 2023-01-26 05:12 UTC
Labels: enhancement
