### ISSUE TITLE
[BUG] Crash for "Manage local game saves" option

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#237] opened 2024-04-06 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Program crashes when I try to use "Manage local game saves"

### Expected Behavior

Something should appear, but certainly not an error message.

### Steps To Reproduce

1. Click the option "Manage local game records".
2. Immediately an error message appears and the program shuts down.

### Environment

```markdown
- Mod Assistant Version: 4.0.0 (but I had it on earlier ones too, certainly on 3.5.2 too)
- OS: Win10 and 11
- Virtualized: No
```

### Anything else?

[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/14895114/crash.log)

I don't know if this is related but the link in the documentation to this option returns "404" xD

**Comment by jtsage** [comment] 2024-04-06 22:17
Huh.  ok, i see where that is happening, but not why.  any chance you wanna do me a huge favor and send me over an archive of your savegames?  maybe include the backup folder?

**Comment by KITT3000** [comment] 2024-04-06 22:20
https://mega.nz/file/pKtACQiL#QfEAwRLTOKtZqHtkhXNLQbGfpMpV8CMKVkDYzoA9D_g

**Comment by jtsage** [comment] 2024-04-06 22:32
thanks.  fwiw, it's save number 8.  but of course it should fail more gracefully than that.

**Comment by jtsage** [comment] 2024-05-06 20:16
all good - how was that folder structured?  I'd prefer to set up MA so it just ignored stuff it can't handle like that

**Comment by SimPaulJack** [comment] 2024-05-06 20:23
For me it was just the standard "SaveGameBackup" folder and then I had another "Manual Save Backup" folder under it where I put other subfolders in that one for the various series I'm making (YT) before starting just in case I run across a FS22 "feature"(not a bug) during play haha. 

For example:
.\SaveGameBackup\
 ManualSaveBackup\
   Series1\
     EpXX\
       savvegame#
       
Of course to solve it I just moved it to the root of the FS22 profile folder so it just ignores it now.

**Comment by jtsage** [comment] 2024-05-06 20:25
cool.  thanks.  I'll do some more checking to make sure it won't error out when it hits unexpected things :)

**Comment by onehandclapping** [comment] 2024-05-13 13:23
Just FYI. I too had a crash with this feature..


`Caught rejection: TypeError: Cannot set properties of undefined (setting 'active')

Origin: [object Promise]

TypeError: Cannot set properties of undefined (setting 'active')
    at C:\Users\Mark\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1690:36
    at async saveGameManager.getInfo (C:\Users\Mark\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1634:3)rejection Timestamp : 2024-05-13T13:05:55.833Z
`
As with SimPaulJack this was caused by a non standard folder "savegame2.calmsden.old" (a backup from ages ago). Deleted that and all well.

**Comment by jtsage** [comment] 2024-05-17 14:20
will be fixed in 4.0.2, later today most likely

**Comment by GrimGadget** [comment] 2024-06-27 23:15
> will be fixed in 4.0.2, later today most likely

I'm using 4.06 and have same issue:


rejection Timestamp : 2024-06-27T23:08:50.778Z

Caught rejection: TypeError: Cannot set properties of undefined (setting 'active')

Origin: [object Promise]

TypeError: Cannot set properties of undefined (setting 'active')
    at C:\Users\Toby\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1690:36
    at async saveGameManager.getInfo (C:\Users\Toby\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1634:3)rejection Timestamp : 2024-06-27T23:09:22.427Z

Caught rejection: TypeError: Cannot set properties of undefined (setting 'active')

Origin: [object Promise]

TypeError: Cannot set properties of undefined (setting 'active')
    at C:\Users\Toby\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1690:36
    at async saveGameManager.getInfo (C:\Users\Toby\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modCheckLib.js:1634:3)

**Comment by jtsage** [comment] 2024-06-27 23:17
Gross. I'll take a look at this later tonight or sometime this weekend

**Comment by GrimGadget** [comment] 2024-06-28 01:00
I just took another look at mine, though.  I had two folders named `savegame1 - Backup A` and `savegame1 - Backup B` where I created manual backups of my main game after what I considered to be key events.

I deleted those two folders and the problem has gone away.  

You still might want to put in a safety net of some sort, though.

**Comment by jtsage** [comment] 2024-06-28 02:22
Just curious - like, those folders were a copy of an existing backup folder?  or one of the individual saves copied over? (I do like to explicitly recreate so I can find exactly where my logic bug is)

**Comment by GrimGadget** [comment] 2024-06-28 17:05
> Just curious - like, those folders were a copy of an existing backup folder? or one of the individual saves copied over? (I do like to explicitly recreate so I can find exactly where my logic bug is)

I copied the save to a new folder, then renamed it from `savegame1 - (Copy)` to `savegame1 - Backup A`

At the time I was receiving this error, I had actually erased all the content from these backup folders because I had decided to abandon the savegame and start over with a different map.

**Comment by jtsage** [comment] 2024-06-28 17:09
ah, so they were empty folders at the time - thank you - that gives me several varieties to test so I can kill this bug off for good.  Appreciate the feedback!

**Comment by jtsage** [comment] 2024-08-18 16:59
this is fixed in the testing version

**Closed by jtsage** 2024-08-18 16:59 UTC
Labels: bug
